/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddComponent: typeof import('./src/components/AddComponent.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    Crud: typeof import('./src/components/crud/components/Crud.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeleteDialog: typeof import('./src/components/DeleteDialog.vue')['default']
    DetailComponent: typeof import('./src/components/DetailComponent.vue')['default']
    DetailsDialog: typeof import('./src/components/DetailsDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditAddComponent: typeof import('./src/components/crud/EditAddComponent.vue')['default']
    GenerationDialog: typeof import('./src/components/GenerationDialog.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    InstanceAddComponent: typeof import('./src/components/crud/InstanceAddComponent.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    ModelAddComponent: typeof import('./src/components/crud/ModelAddComponent.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RelatedInstanceComponent: typeof import('./src/components/crud/RelatedInstanceComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Step: typeof import('primevue/step')['default']
    StepItem: typeof import('primevue/stepitem')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    TestModelComponent: typeof import('./src/components/crud/TestModelComponent.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Timeline: typeof import('primevue/timeline')['default']
    Toast: typeof import('primevue/toast')['default']
    VersionInstDialog: typeof import('./src/components/VersionInstDialog.vue')['default']
  }
}
